name: CI

on: push

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v7

      - name: Configurar Python 3
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Instalar pytest
        run: pip install pytest -r requirements.txt

      - name: Executar testes
        run: pytest